### ISSUE TITLE
Generated Resources should use the correct URLs

### ISSUE THREAD

**Issue by dtest** [GoogleCloudPlatform/spanner-migration-tool#614]
## Expected Behavior
The URLs of generated resources should point to console.cloud.google.com

## Actual Behavior
[They](https://github.com/GoogleCloudPlatform/spanner-migration-tool/blob/d648bbda0f0c5a51fa6e80ff40bee48e0a774a39/webv2/web.go#L2220C3-L2249) currently don't

## Steps to Reproduce the Problem

1. Proceed through a zero-downtime migration
1. Get the list of generated resources
1. Notice the URLs are internal URLs.

**Comment by shreyakhajanchi** [comment]
Fixed
